version: '3.4'
services:
  races-services:
    image: races-services:1.0.0
    container_name: races-services
    volumes:
      - /races/logs/services:/logs:z
      - /races/history/services:/history:z
    environment:
      DATABASE: 'races-database:3306'
      DB_USER: 'racemgmt'
      DB_PASS: 'RaceManagement'
      UPLOAD_PATH: '/history'
      ROUTELOG: '/logs'
      PORT: '8081'
    ports:
      - 8081:8081/tcp
    restart: always
    links:
      - races-database:races-database
    depends_on: 
      - races-database
  races-database:
    image: mysql:5.7
    container_name: races-database
    volumes:
      - /races/mysql/dumps:/dumps:z
      - /races/mysql/scripts:/scripts:z
      - /races/mysql/data:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: 'racesManagement'
    ports:
      - 3306:3306/tcp
    restart: always
    user: mysql:mysql
  races-portal:
    image: races-portal:1.0.0
    container_name: races-portal
    volumes:
      - /races/logs/portal:/logs:z
      - /races/history/portal:/history:z
    environment:
      SERVICES: 'http://races-services:8081'
      UPLOAD_PATH: '/history'
      ROUTELOG: '/logs'
    ports:
      - 8080:8080/tcp
    restart: always
    links:
      - races-services
    depends_on: 
      - races-services
