@hostname=localhost
@protocol=http
@port=8081
@host={{protocol}}://{{hostname}}:{{port}}
@idReglamento=1
@idPuntuacion=81
@idPiloto=4
@idEquipo=3
@idCampeonato=2
@idInscripcion=2
@idGp=4
@idSesionGP=1
@idResultado=6
@idSancion=1
### 1 - REGLAMENTOS
# @name buscarReglamentos
GET {{host}}/reglamento HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
# @name crearReglamento
POST {{host}}/reglamento HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"descripcion": "Reglamento oficial de F1 2021",
    "nEntrenamientos":3,
	"nClasificaciones":1,
	"nCarreras":1,
	"nPilotos":20,
	"nEquipos":10
}
###
# @name modificarReglamento
PUT {{host}}/reglamento/{{idReglamento}} HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"descripcion": "Reglamento oficial de F1 2020",
    "nEntrenamientos":3,
	"nClasificaciones":1,
	"nCarreras":1,
	"nPilotos":20,
	"nEquipos":10
}

###
# @name eliminarReglamento
DELETE {{host}}/reglamento/{{idReglamento}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

###
### 2 - Sesiones
# @name buscarSesiones
GET {{host}}/sesion HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMzEwMTgsImV4cCI6MTU4NzIzNDYxOCwianRpIjoiLUJsLWtuVzFVTVUydGlMNnFwNXcydyIsImtpZCI6Ik1NUiJ9.UUwF9b1B6UyT5htu9Yyk-glaprlGG2x9PgOBZJXxzIliXYRKZzajdeBCsC-3wPdl8duA5dbTCDEESFo-JAed5FQE417bBq3pXv0NzBmP7YBSYrCfSSg1B4Z87TWLQGR7z8nRd1iwM0yPj07z8EtOPXofntLFGcGDaqKKGhOINvzWV_r12mPcuBbac9KoqiJ9Zj4bW_CwBANXYk6cO7v3M5k073pG0pisE2V5ecS8HY6IOF4SgUN4TTNzL4DWtSEMSnfQOQX_qNyb6s14TK8RITD1jubQyZvOm-flhb1bstOB5_cn3fvsretDY58WJbgUvoYwmAZesiqsG1VXzyWTnA

###
### 3 - Tipo Sesion
# @name buscarTipoSesiones
GET {{host}}/tsesion HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

###
### 4 - Puntuaciones
# @name buscarPuntuaciones
GET {{host}}/puntuacion HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

###
# @name modificarPuntuaciones
PUT {{host}}/puntuacion/{{idPuntuacion}} HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
    "idSesion": "5",
    "puntos": 25,
    "posicion":1
}
###
### 5 - Pilotos
# @name buscarPilotos
GET {{host}}/piloto
X-Races-User: MAXTDI
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODczMjEzMDksImV4cCI6MTU4NzMyNDkwOSwianRpIjoiWjk3b2Vnd2NadFJ0MlBxck5jaGhEZyIsImtpZCI6Ik1BWFRESSJ9.YMgD5RNToPIPaYuidMENnAXv7XGzFSK4cxAk4KznR-yhZ_AfRzLdqbYv-ohRe3zHui2o6iAJEfc0aMHqozabMP67U2ASKLGlL7AR57fIuy0gndFMzb2cQc7PYP4ifs9VDv2i2iDbNPO_siF7ssizx4QMpoUQzxQ8OmhrxD8VKoAU98wIEJQuExteoh_B0QQVRn7lY53KI49sW6NISPBZc4S3f0uOIUltjAUEV619VuQm3Z1MVDnipPWIL7W4_ZtEfghkDjWx65QnyA7E8CoLDf4h1Etfa0Zw-RqQ1zHZguDKaXWgqyI3pZz1lPD5aVIZpTz0cr2G2CMQA_D2ogVU7w

###
# @name crearPiloto
POST {{host}}/piloto HTTP/1.1
Content-Type: application/json

{
	"nombre":"Maximino",
	"apellido":"Mañanes",
	"apodo":"MMR",
	"password": "temporal",
	"admin": true
}
###
# @name eliminarPiloto
DELETE {{host}}/piloto/{{idPiloto}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

###
# @name validarPiloto
POST {{host}}/login HTTP/1.1
Authorization: Basic TUFYVERJOnRlbXBvcmFs
###
### 6 - Equipos
# @name crearEquipo
POST {{host}}/equipo HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"nombre":"Scuderia Ferrari F1 Team",
	"alias":"Ferrari"
}
###
# @name buscarEquipo
GET {{host}}/equipo HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
# @name modificarEquipo
PUT {{host}}/equipo/{{idEquipo}} HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"nombre":"Scuderia Ferrari F1",
	"alias":"Ferrari"
}

###
# @name eliminarEquipo
DELETE {{host}}/equipo/{{idEquipo}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
### 7 - Campeonatos
# @name buscarCampeonato
GET {{host}}/campeonato HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
# @name crearCampeonato
POST {{host}}/campeonato HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"nombre":"F1",
	"descripcion":"Campeonato oficial de Formula 1",
	"temporada":"2021",
	"reglamento":1
}
###
# @name modificarCampeonato
PUT {{host}}/campeonato/{{idCampeonato}} HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"nombre":"F1",
	"descripcion":"Campeonato oficial de Formula 1 2021",
	"temporada":"2021"
}
###
# @name eliminarCampeonato
DELETE {{host}}/campeonato/{{idCampeonato}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
### 8 - Inscripciones
# @name buscarInscripcion
GET {{host}}/inscripcion HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
# @name crearInscripcion
POST {{host}}/inscripcion HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"idCampeonato": {{idCampeonato}},
	"idEquipo": {{idEquipo}},
	"idPiloto": {{idPiloto}}
}
###
# @name eliminarInscripcion
DELETE {{host}}/inscripcion/{{idInscripcion}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
### 9 - Grandes Premios
# @name buscarGP
GET {{host}}/gp HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMzY4NDIsImV4cCI6MTU4NzI0MDQ0MiwianRpIjoicDlheHpBZTlpZWxsZnljM3FlMWs0ZyIsImtpZCI6Ik1NUiJ9.F4NbHVRkPsZtetQXYdGoelm_3uC8ZBJN2OICrKqVLBmen7RHPeX68fWrkVNqlQOWJjvA_RdJ_NfQEF265tnpk8WxgRo2pA7ByRJbwMbbSAhDm_UO4LZp5ou19dC13EgEJM-5FgrF3iv5Qh1RMxjpJe8wdamNKhXE3VFW256OD0fZPP1xPpVlZ3kWY0EbHst2MnyTwDZP-AuSyoSqq9kBkH2rxoUMBfj2XqM92UhLM_HuMsDFR6f2pcNv1GqIhSpqN72YOieNeRyTGTU3wNiv_3ZaN_iIlG8eoFUwAc4UZqZAkn7D5bSOM0s5wA-nE6FqbHeYbuS4JyOl4Vm_BOf1GQ
###
# @name crearGP
POST {{host}}/gp HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"idCampeonato":{{idCampeonato}},
	"ubicacion":"ESPAÑA",
	"fecha": "2021-05-05"
}
###
# @name eliminarGP
DELETE {{host}}/gp/{{idGp}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
### 10 - Sesiones Grandes Premios
# @name buscarSesionesGP
GET {{host}}/sesionGP HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
# @name modificarSesionGP
PUT {{host}}/sesionGP/{{idSesionGP}} HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"fecha":"2021-05-03"
}
###
### 11 - Resultados
# @name buscarResultados
GET {{host}}/resultado HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMzY4NDIsImV4cCI6MTU4NzI0MDQ0MiwianRpIjoicDlheHpBZTlpZWxsZnljM3FlMWs0ZyIsImtpZCI6Ik1NUiJ9.F4NbHVRkPsZtetQXYdGoelm_3uC8ZBJN2OICrKqVLBmen7RHPeX68fWrkVNqlQOWJjvA_RdJ_NfQEF265tnpk8WxgRo2pA7ByRJbwMbbSAhDm_UO4LZp5ou19dC13EgEJM-5FgrF3iv5Qh1RMxjpJe8wdamNKhXE3VFW256OD0fZPP1xPpVlZ3kWY0EbHst2MnyTwDZP-AuSyoSqq9kBkH2rxoUMBfj2XqM92UhLM_HuMsDFR6f2pcNv1GqIhSpqN72YOieNeRyTGTU3wNiv_3ZaN_iIlG8eoFUwAc4UZqZAkn7D5bSOM0s5wA-nE6FqbHeYbuS4JyOl4Vm_BOf1GQ
###
# @name uploadResultados
POST {{host}}/resultado/load/{{idSesionGP}}
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

file
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="../racesPortal/uploadFile.txt"
Content-Type: text/plain

MMR;1:20.000;1:21.401;1:20.002;1:20.003;1:20.004;1:20.005;1:20.006;1:20.007;1:20.008
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
### 12 - Vueltas
# @name buscarVueltas
GET {{host}}/vuelta HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
### 13 - Sanciones
# @name buscarSancion
GET {{host}}/sancion HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
# @name crearSancion
POST {{host}}/sancion HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"idResultado": {{idResultado}},
	"descripcion": "Test Sancion",
	"puntos": 1,
	"tiempo": 1000
}
###
# @name modificarSancion
PUT {{host}}/sancion/{{idSancion}} HTTP/1.1
Content-Type: application/json
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ

{
	"descripcion": "Test Sancion Mod",
	"puntos": 1,
	"tiempo": 1500
}
###
# @name eliminarSancion
DELETE {{host}}/sancion/{{idSancion}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
### 14 - Clasificaciones
# @name obtenerClasificacionGP
GET {{host}}/clasificacion/gp/{{idGp}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###
# @name obtenerClasificacionCampeonato
GET {{host}}/clasificacion/campeonato/{{idCampeonato}} HTTP/1.1
X-Races-User: MMR
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODcyMTUwODIsImV4cCI6MTU4NzIxODY4MiwianRpIjoiRVZiVU1STFpkTkMyaHA3dURqMXYwZyIsImtpZCI6Ik1NUiJ9.TJOue5Ij4-xfh8F3XPgBZ9qlIXT5oDWxJMoO_VWyAq4zN_FEgSdYdNGhQ2Y1wnSWeCnSF-Ds5WWjRU5sHwUoou7ZMB_qwVTHw-o_7yeKdt6yygLYch2G51bFAdHMuDn5Ps0CwVi5NH7qzKfAqvyA2niCWbQcRvhVpgbdmbDq5Sypf-lHnx9Nu053dnePA1CncbjV4JVYqKdQJvHB6xB9IBwzalQVV9TOVgOC6lZnoa3T2p5P7JqMcIhStJpWIZlY5YQjeWS0RdlT7RCLQGy-3_ejkddkoNM0TukEwxUSnQBEcI-0OGCIzS-vavrwt6wbPz3efhi8ZBE2kJNJI9-AKQ
###