spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: karsmarasUsers
    password: karsmaras
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 18080