spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/race_management_db
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
server:  port: 8081