spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/karsmaras
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
